services:
  load-balancer:
    image: nginx:latest
    ports:
      - "9999:9999"
    networks:
      - backend
    volumes:
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend-1
      - backend-2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

  redis:
    image: redis:latest
    container_name: rinha-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "100MB"

  backend-1: &backend
    build: .
    container_name: rinha-backend 
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "100MB"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - PORT=8080 
      - WORKERS=5
      - QUEUE="payment-queue"
      - HASH_DEFAULT="payments-default"
      - HASH_FALLBACK="payments-fallback"
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080

  backend-2:
    <<: *backend
    container_name: rinha-backend-2

volumes:
  redis_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
