services:

  load-balancer:
    image: nginx:latest
    ports:
      - 9999:9999
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-1
      - backend-2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

  redis:
    image: redis:latest
    container_name: rinha-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "100MB"

  backend-1: &backend
    build: .
    container_name: rinha-backend 
    hostname: backend-1
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "100MB"
    environment:
      - PORT: 8080
      - PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
      - PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080

  backend-2: 
    <<: *backend
    container_name: rinha-backend-2
    hostname: backend-2

volumes:
  redis_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
